---
name: charmory
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python = 3.10
  - conda-forge::pip >= 23.0.0
  - conda-forge::curl
  - conda-forge::git
  - conda-forge::libarchive
  - conda-forge::gcc_linux-64
  - pytorch::pytorch
  - pytorch::torchvision
  - pip:
    - --editable .
