---
site_name: Armory
site_url: https://gitlab.jatic.net/jatic/twosix/armory/
site_author: Two Six Technologies

docs_dir: docs/
site_dir: public/

repo_url: https://gitlab.jatic.net/jatic/twosix/armory/
edit_uri: blob/master/documentation/

theme:
    name: material
    locale: en
    highlightjs: true

plugins:
  - exclude:
      glob:
        - original/*

nav:
  - Home: index.md
  - Getting Started: getting_started.md
