---
site_name: Armory
site_url: https://gitlab.jatic.net/jatic/twosix/armory/
site_author: Two Six Technologies

docs_dir: docs/
site_dir: public/

repo_url: https://gitlab.jatic.net/jatic/twosix/armory/
edit_uri: blob/master/documentation/

theme:
    name: readthedocs
    locale: en
    highlightjs: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - FAQs: faqs.md
  - Environment:
      - Command Line: command_line.md
      - Docker: docker.md
      - No-Docker: no_docker_mode.md
  - Experiments:
      - Configuration Files: configuration_files.md
      - Baseline Models: baseline_models.md
      - External Repos: external_repos.md
      - Sweep Attacks: sweep_attacks.md
  - Evaluation Scenarios:
      - Evasion: scenarios.md
      - Poisoning: poisoning.md
  - Data:
      - Datasets: datasets.md
      - Integrating TFDS Datasets: integrate_tensorflow_datasets.md
      - Adversarial Datasets: adversarial_datasets.md
      - Dataset Licensing: dataset_licensing.md
  - Measurment and Instrumentation:
      - Exporting Data: exporting_data.md
      - Logging: logging.md
      - Metrics: metrics.md
  - Developers:
      - Contributing: contributing.md
      - Style: style.md
      - Testing: developers/testing.md

