[project]
requires-python = ">=3.8"

name = "armory-matrix"
description = "Armory Evaluation Matrix Library"
readme = "README.md"
dynamic = ["version"]
license = "MIT"
authors = [{ name = "Two Six Technologies", email = "armory@twosixtech.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = []

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[tool.hatch.build]
ignore-vcs = false
reproducible = true
directory = "dist"
sources = ["src"]
include = ["src/", "LICENSE", "pyproject.toml", "README.md"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
source = "vcs"
path = "src/armory/matrix/version.py"

[tool.hatch.version.raw-options]
root = "../"
version_scheme = "post-release"

[tool.hatch.build.hooks.vcs]
version-file = "src/armory/matrix/version.py"
template = """
# coding: utf-8
# File automatically generated by setuptools_scm.
# Do not change or track in version control.
__version__ = {version!r}
version_tuple = {version_tuple!r}
"""

[tool.setuptools_scm]
# the presence of this empty block stops setuptools_scm from complaining

[tool.taskipy.tasks]
test = "python -m pytest -m unit"