# coding: utf-8
# File automatically generated by setuptools_scm.
# Do not change or track in version control.
__version__ = "0.16.6.post3+g40ca1472.d20230314"
version_tuple = (0, 16, 6, "g40ca1472.d20230314")
