---
site_name: Armory
site_url: https://gitlab.jatic.net/jatic/twosix/armory/
site_author: Two Six Technologies

# Both `docs` and `site` directories are one level up
docs_dir: ../docs/
site_dir: ../public/

repo_url: https://gitlab.jatic.net/jatic/twosix/armory/
edit_uri: blob/master/documentation/

use_directory_urls: false

theme:
    name: material
    locale: en
    highlightjs: true

plugins:
  - exclude:
      glob:
        - original/*
  - mkdocstrings:
      handlers:
          python:
              paths: [../library/src]
              options:
                  show_source: false
                  show_submodules: true
                  show_root_heading: true
                  show_root_full_path: true
                  show_category_heading: true
                  signature_crossrefs: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Developers Guide: developers/README.md
  - Exporting Data: exporting_data.md
  - API Reference:
    - Ingestion and Adaptation:
      - Datasets: reference/dataset.md
      - Transforms: reference/transforms.md
      - Models: reference/model.md
    - Evaluation:
      - Configuration: reference/evaluation.md
      - Label Targeters: reference/labels.md
      - Metrics: reference/metric.md
      - Exporters: reference/export.md
      - Profilers: reference/profiler.md
    - Tasks: reference/task.md
    - Engines: reference/engine.md
    - Tracking: reference/track.md
    - Utilities: reference/utils.md
