---
# yamllint disable
name: 🐛📦 Build & Test

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+.[0-9]+'   # release branches have the form v1.9.x
      - 'rc[0-9]+.[0-9]+.[0-9]+'  # release candidate branches

  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'rc[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_BUILDKIT: 1


jobs:
  scan-lint-build:
    uses: ./.github/workflows/1-scan-lint-build.yml

  test-stand-alone-builds:
    needs: scan-lint-build
    uses: ./.github/workflows/2-test-stand-alone.yml

  test-docker-builds:
    uses: ./.github/workflows/3-test-docker.yml
