name: 🙈 🙉 🙊 Scan & Lint

on: workflow_call

jobs:
  code-quality:
    name: 🦄 Code Quality
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu ]
        python-version: [ 3.9 ]
    steps:
      - name: 🐄 Got git?
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get history and tags for SCM versioning to work
      - name: 📩 Checkout the Source
        run: |
          git fetch --prune --unshallow || true
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          # Verify .git folder
          if [ ! -d "./.git" ]; then
            echo "Expected ./.git folder to exist"
            exit 1
          fi

      - name: 🐍 Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🐍 Switch Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🌱 Setup Test Enviroment
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: ⚙️ Install Armory
        shell: bash
        run: |
          pip install --no-compile --editable '.[developer]'
          armory configure --use-defaults

      - name: 🚀 Run commit hooks
        env:
          ARMORY_VERSION: ${{ env.ARMORY_VERSION }}
        run: |
          echo $ARMORY_VERSION
          echo ${{ env.ARMORY_ROOT }}

          echo "💄 Running pre-commit hooks for Armory version ${VERSION}"

          bash tools/pre-commit.sh
        # if [ $? -ne 0 ]; then
        #   echo "🚨 Pre-commit hooks failed. Please run 'pre-commit run --all-files' locally to fix the issues 🚑"
        #   exit 1
        # fi
